import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { LkEdoClient } from './client';

const here = dirname(fileURLToPath(import.meta.url));

describe('lk-client (compact, backend-only)', () => {
  it('fails closed without service token', async () => {
    const client = new LkEdoClient({ baseUrl: 'http://localhost:8080', internalToken: '' });
    await expect(client.listLocations()).rejects.toThrow('LK_EDO_INTERNAL_TOKEN');
  });

  it('sends service Bearer token (never user JWT)', async () => {
    let authHeader = '';
    const client = new LkEdoClient({
      baseUrl: 'http://lk:8080',
      internalToken: 'svc-secret',
      fetchImpl: (async (url: unknown, init: unknown) => {
        authHeader = (init as { headers: Record<string, string> }).headers.Authorization;
        return { ok: true, json: async () => [] };
      }) as typeof fetch,
    });
    await client.listLocations();
    expect(authHeader).toBe('Bearer svc-secret');
  });

  it('pins the narrow EDO spec (4 paths only)', () => {
    const spec = JSON.parse(readFileSync(join(here, '..', 'openapi', 'edo.json'), 'utf8'));
    const paths = Object.keys(spec.paths);
    expect(paths.sort()).toEqual(
      [
        '/api/internal/edo/v1/departments',
        '/api/internal/edo/v1/employees',
        '/api/internal/edo/v1/locations',
        '/api/internal/edo/v1/positions',
      ].sort(),
    );
  });

  it('is actually generated from the narrow spec (no hand-written broad client)', () => {
    const generated = readFileSync(join(here, 'generated', 'api.ts'), 'utf8');
    expect(generated).toMatch(/Generated by orval/);
    expect(generated).toMatch(/edoListEmployees/);
    expect(generated).toMatch(/edoListLocations/);
    expect(generated).toMatch(/edoListPositions/);
    expect(generated).toMatch(/edoListDepartments/);
    expect(generated).not.toMatch(/\/api\/internal\/edo\/v1\/organizations/);
  });

  it('handwritten adapter reuses generated URL helpers (no duplicated paths)', () => {
    const src = readFileSync(join(here, 'client.ts'), 'utf8');
    expect(src).toMatch(/getEdoListEmployeesUrl/);
    expect(src).toMatch(/getEdoListLocationsUrl/);
    expect(src).not.toMatch(/\/api\/internal\/edo\/v1\/employees\?/);
  });

  it('generate script uses explicit package root (no packages/packages bug)', () => {
    const script = readFileSync(join(here, '..', 'scripts', 'generate.mjs'), 'utf8');
    expect(script).toMatch(/packageRoot/);
    expect(script).not.toMatch(/join\(root, 'packages', 'lk-client'/);
  });
});
