import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { LkEdoClient, LkAuthError, LkContractError } from './client';

const here = dirname(fileURLToPath(import.meta.url));

describe('lk-client (compact, backend-only)', () => {
  it('fails closed without service token', async () => {
    const client = new LkEdoClient({ baseUrl: 'http://localhost:8080', internalToken: '' });
    await expect(client.listLocations()).rejects.toThrow('LK_EDO_INTERNAL_TOKEN');
  });

  it('sends service Bearer token (never user JWT)', async () => {
    let authHeader = '';
    const client = new LkEdoClient({
      baseUrl: 'http://lk:8080',
      internalToken: 'svc-secret',
      fetchImpl: (async (url: unknown, init: unknown) => {
        authHeader = (init as { headers: Record<string, string> }).headers.Authorization;
        return { ok: true, json: async () => [] };
      }) as typeof fetch,
    });
    await client.listLocations();
    expect(authHeader).toBe('Bearer svc-secret');
  });

  it('pins the narrow EDO spec (4 paths only)', () => {
    const spec = JSON.parse(readFileSync(join(here, '..', 'openapi', 'edo.json'), 'utf8'));
    const paths = Object.keys(spec.paths);
    expect(paths.sort()).toEqual(
      [
        '/api/internal/edo/v1/departments',
        '/api/internal/edo/v1/employees',
        '/api/internal/edo/v1/locations',
        '/api/internal/edo/v1/positions',
      ].sort(),
    );
  });

  it('is actually generated from the narrow spec (no hand-written broad client)', () => {
    const generated = readFileSync(join(here, 'generated', 'api.ts'), 'utf8');
    expect(generated).toMatch(/Generated by orval/);
    expect(generated).toMatch(/edoListEmployees/);
    expect(generated).toMatch(/edoListLocations/);
    expect(generated).toMatch(/edoListPositions/);
    expect(generated).toMatch(/edoListDepartments/);
    expect(generated).not.toMatch(/\/api\/internal\/edo\/v1\/organizations/);
  });

  it('handwritten adapter reuses generated URL helpers (no duplicated paths)', () => {
    const src = readFileSync(join(here, 'client.ts'), 'utf8');
    expect(src).toMatch(/getEdoListEmployeesUrl/);
    expect(src).toMatch(/getEdoListLocationsUrl/);
    expect(src).not.toMatch(/\/api\/internal\/edo\/v1\/employees\?/);
  });

  it('generate script uses explicit package root (no packages/packages bug)', () => {
    const script = readFileSync(join(here, '..', 'scripts', 'generate.mjs'), 'utf8');
    expect(script).toMatch(/packageRoot/);
    expect(script).not.toMatch(/join\(root, 'packages', 'lk-client'/);
  });
});

describe('lk-client hardening (Etap 4)', () => {
  function clientWith(fetchImpl: typeof fetch, opts: Record<string, unknown> = {}) {
    return new LkEdoClient({ baseUrl: 'http://lk:8080', internalToken: 'svc-secret', fetchImpl, ...opts });
  }

  it('retries transient 503 with backoff, then succeeds', async () => {
    let calls = 0;
    const client = clientWith((async () => {
      calls += 1;
      if (calls < 3) return { ok: false, status: 503, text: async () => 'busy' };
      return { ok: true, json: async () => [] };
    }) as typeof fetch);
    const res = await client.listLocations();
    expect(res).toEqual([]);
    expect(calls).toBe(3);
  });

  it('never retries permanent 401 (auth) and throws safe error without body', async () => {
    let calls = 0;
    const client = clientWith((async () => {
      calls += 1;
      return { ok: false, status: 401, text: async () => 'secret-body-with-PII-Иванов' };
    }) as typeof fetch);
    await expect(client.listLocations()).rejects.toBeInstanceOf(LkAuthError);
    expect(calls).toBe(1);
    await expect(client.listLocations()).rejects.toThrow(/401.*locations/);
    await expect(client.listLocations()).rejects.not.toThrow(/Иванов/);
  });

  it('missing nextCursor is a contract error (never end-of-snapshot), no retry', async () => {
    let calls = 0;
    const client = clientWith((async () => {
      calls += 1;
      return { ok: true, json: async () => ({ items: [] }) };
    }) as typeof fetch);
    await expect(client.listEmployeesPage(500, null)).rejects.toBeInstanceOf(LkContractError);
    expect(calls).toBe(1);
  });

  it('validates page shape before apply (non-array items rejected)', async () => {
    const client = clientWith((async () => ({
      ok: true,
      json: async () => ({ items: 'not-an-array', nextCursor: null }),
    })) as typeof fetch);
    await expect(client.listEmployeesPage(500, null)).rejects.toThrow(/contract/i);
  });

  it('finishes only on valid nextCursor === null', async () => {
    const client = clientWith((async () => ({
      ok: true,
      json: async () => ({ items: [], nextCursor: null }),
    })) as typeof fetch);
    const page = await client.listEmployeesPage(500, null);
    expect(page.nextCursor).toBeNull();
  });
});
